### ISSUE TITLE
how to use where condition with date?

### ISSUE THREAD

**Issue by hsuanyi-chou** [t-k/swr-firestore#96]
Hi,
I want to query my data with date condition in hook.

but causing infinite loop and never return data.
```
  const {
    data
  } = useGetDocs<User>(
{
          path: `users`,
          where: [['created', '>=', new Date()]], // If I commented out, it works normally.
          orderBy: [
            ['updated', 'desc'],
          ],
          parseDates: ['updated', 'created'],
        }
  );
```

how should do a query with date condition?

thanks in advance.

**Comment by hsuanyi-chou** [comment]
@t-k thank you so much!
didn't think about the `new Date()` been called each time

and thank you for combining firebae with swr.
it's an awesome library and help me a lot!

**Comment by t-k** [comment]
@hsuanyi-chou Thank you for your confirmation. I'm glad I could help you.
